pipeline {
    agent none

    stages {

        stage('Back-end Compile & Run') {
            agent {
                docker {
                    image 'maven:3.8.1-adoptopenjdk-11'
                }
            }

            steps {
                sh 'java -version'
                sh 'javac HelloWorld.java'
                sh 'java HelloWorld'
            }
        }

        stage('Front-end') {
            agent {
                docker {
                    image 'node:16-alpine'
                }
            }

            steps {
                sh 'node --version'
            }
        }
    }
}
